# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.16

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: git config user.name "${CIRCLE_USERNAME}"
      - run: git config user.email "${CIRCLE_USERNAME}@users.noreply.github.com"

      - add_ssh_keys:
                fingerprints:
                  - "40:bd:39:1e:7a:e4:03:85:f1:60:42:af:8d:ec:2e:5b"

      # run deploy!
      - run: yarn deploy
